# Generated by Django 6.0.5 on 2026-05-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.contactinfo'),
        ),
    ]
