# Generated by Django 6.0.5 on 2026-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review_reviewpage_homepage_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringenpage',
            name='video',
            field=models.URLField(blank=True, help_text='Plak hier een YouTube link'),
        ),
    ]
