# Generated by Django 6.0.5 on 2026-05-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ervaringenpage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Plak hier Google Maps embed link'),
        ),
    ]
