# Generated by Django 6.0.5 on 2026-05-25 11:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactinfo_address_contactinfo_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
