# Generated by Django 6.0.5 on 2026-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='fb',
            field=models.URLField(blank=True, help_text='Plak hier de Facebook link'),
        ),
    ]
