# Generated by Django 6.0.5 on 2026-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='wa',
            field=models.URLField(blank=True, help_text='WhatsApp link'),
        ),
    ]
