# Generated by Django 6.0.5 on 2026-05-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_wa'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beschrijving', models.TextField(blank=True)),
                ('afbeelding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='products',
            field=models.ManyToManyField(blank=True, to='home.product'),
        ),
    ]
