# Generated by Django 6.0.5 on 2026-06-01 17:19

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_webshoppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshoppage',
            name='products',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.product'),
        ),
    ]
